add modulemap and CBBSwift3RemoteExport to support Swift3
cross-border-bridge/function-channel-ios pull request #8
Opened 2017-07-03 15:38 UTC by kentdotn

CBBFunctionChannelをSwiftから引けるようにmodulemapを追加します。

また、Swift3のメソッド名生成規則に対応するCBBSwift3RemoteExportを追加します。

2017-07-03 15:38 UTC, kentdotn commented on CBBFunctionChannel.podspec
> +  s.module_map = "CBBFunctionChannel.modulemap"
modulemapとpodspecのこの修正で、とりあえずSwiftから呼べるようになります。

2017-07-03 15:40 UTC, kentdotn commented on CBBFunctionChannel/CBBRemoteExportUtility.m
> +                }
Swift3で定義したメソッドの第１引数には自動的に `With` がついてしまうので、これを外すようにしています。
なお、Swift側のコードで `func foo(_ arg1: T1, arg2: T2, ...)` のように明示的に `_` を使えばこの問題は起こりません。

`CBBSwift3RemoteExport` の導入に伴うコード変更が大きすぎるということなら、
Swiftでは「第１引数は `_` 付きで定義すること」という仕様に倒してしまうのも手だと思います。

2017-07-03 15:42 UTC, kentdotn commented
https://github.com/cross-border-bridge/data-channel-ios/pull/6 がマージされ、バージョンが上がったら、依存先の指定も合わせて更新するのが望ましいです。

2017-07-04 12:21 UTC, suzukiplan requested changes

2017-07-04 12:21 UTC, suzukiplan commented on CBBFunctionChannel/CBBRemoteExport.h
> +@protocol CBBSwift3RemoteExport <CBBRemoteExport>
Swiftは原則 __最新バージョンのみサポート__ という（つまり、対Swift向けのコードに関しては一切の下位互換性を保つ必要が無く、言語バージョンアップに伴う破壊的変更が自由にできるものとする）方針にすべきだと考えています。
なので、モジュール名に言語バージョン ( `3` ) は付けるべきでないと思います。

2017-07-04 12:21 UTC, suzukiplan commented on CBBFunctionChannel/CBBRemoteExportUtility.m
> +    CBBMethodNamingConvension_Swift3,
これも `3` を付けるべきではないです。

2017-07-04 18:53 UTC, kentdotn commented on CBBFunctionChannel/CBBRemoteExport.h
> +@protocol CBBSwift3RemoteExport <CBBRemoteExport>
その原則自体は了解なので削るのは構わないのですが、
その場合、せめてsemverについては同じマイナーバージョンで同一のSwiftバージョンに対応するようにして欲しいです。

それと、そういう話なのであれば、https://github.com/cross-border-bridge/function-channel-ios/pull/8#discussion_r125317325 でも書いているように、`CBBSwift3RemoteExport` の導入も見送ってもらい、「Swiftでは第１引数は必ず _ 付きで定義すること」という仕様ということにしてしまえば、Swiftの命名規則の互換性に煩わされることもないように思います。

2017-07-05 03:12 UTC, suzukiplan commented on CBBFunctionChannel/CBBRemoteExport.h
> +@protocol CBBSwift3RemoteExport <CBBRemoteExport>
@saiten さん的にも問題無ければ

> 「Swiftでは第１引数は必ず _ 付きで定義すること」という仕様

とする方向でいきたいところです。

2017-07-05 03:16 UTC, suzukiplan commented on CBBFunctionChannel/CBBRemoteExport.h
> +@protocol CBBSwift3RemoteExport <CBBRemoteExport>
_Swift specialな箇所を増やしたくないので_

2017-07-05 05:56 UTC, saiten commented on CBBFunctionChannel/CBBRemoteExport.h
> +@protocol CBBSwift3RemoteExport <CBBRemoteExport>
そですね。自分も`_`付きで定義することにしてしまう方が良い気がします。

2017-07-06 01:38 UTC, suzukiplan commented
という訳で、このPRは一旦閉じてしまいます。

2017-07-06 01:38 UTC, closed without merging